//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ExpenseMe.Domain
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ExpenseMeModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ExpenseMeModelContainer object using the connection string found in the 'ExpenseMeModelContainer' section of the application configuration file.
        /// </summary>
        public ExpenseMeModelContainer() : base("name=ExpenseMeModelContainer", "ExpenseMeModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpenseMeModelContainer object.
        /// </summary>
        public ExpenseMeModelContainer(string connectionString) : base(connectionString, "ExpenseMeModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpenseMeModelContainer object.
        /// </summary>
        public ExpenseMeModelContainer(EntityConnection connection) : base(connection, "ExpenseMeModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Expense> Expenses
        {
            get
            {
                if ((_Expenses == null))
                {
                    _Expenses = base.CreateObjectSet<Expense>("Expenses");
                }
                return _Expenses;
            }
        }
        private ObjectSet<Expense> _Expenses;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Expenses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExpenses(Expense expense)
        {
            base.AddObject("Expenses", expense);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseMeModel", Name="Expense")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Expense : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Expense object.
        /// </summary>
        /// <param name="expenseId">Initial value of the ExpenseId property.</param>
        public static Expense CreateExpense(global::System.Int32 expenseId)
        {
            Expense expense = new Expense();
            expense.ExpenseId = expenseId;
            return expense;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExpenseId
        {
            get
            {
                return _ExpenseId;
            }
            set
            {
                if (_ExpenseId != value)
                {
                    OnExpenseIdChanging(value);
                    ReportPropertyChanging("ExpenseId");
                    _ExpenseId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ExpenseId");
                    OnExpenseIdChanged();
                }
            }
        }
        private global::System.Int32 _ExpenseId;
        partial void OnExpenseIdChanging(global::System.Int32 value);
        partial void OnExpenseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ExpenseDate
        {
            get
            {
                return _ExpenseDate;
            }
            set
            {
                OnExpenseDateChanging(value);
                ReportPropertyChanging("ExpenseDate");
                _ExpenseDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpenseDate");
                OnExpenseDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ExpenseDate;
        partial void OnExpenseDateChanging(Nullable<global::System.DateTime> value);
        partial void OnExpenseDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Spent
        {
            get
            {
                return _Spent;
            }
            set
            {
                OnSpentChanging(value);
                ReportPropertyChanging("Spent");
                _Spent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Spent");
                OnSpentChanged();
            }
        }
        private Nullable<global::System.Double> _Spent;
        partial void OnSpentChanging(Nullable<global::System.Double> value);
        partial void OnSpentChanged();

        #endregion

    
    }

    #endregion

    
}
